# Generated by Django 5.0.1 on 2024-05-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pfp',
            field=models.ImageField(blank=True, upload_to='templates/files/pfp'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
