# Generated by Django 5.0.1 on 2024-05-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_userinfo_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pfp',
            field=models.ImageField(blank=True, upload_to='static/images/icons'),
        ),
    ]
