# Generated by Django 5.0.1 on 2024-05-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_alter_userinfo_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='pfp',
        ),
    ]
