# Generated by Django 5.0.1 on 2024-05-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_remove_userinfo_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalName', models.CharField(max_length=50)),
                ('pfp', models.ImageField(blank=True, upload_to='icons/')),
            ],
        ),
    ]
