# Generated by Django 5.0.1 on 2024-05-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0008_usericon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usericon',
            name='pfp',
            field=models.ImageField(blank=True, upload_to='static/images/icons'),
        ),
    ]
