# Generated by Django 5.0.1 on 2024-05-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0009_alter_usericon_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usericon',
            name='pfp',
            field=models.ImageField(blank=True, default='static/images/icon.png', upload_to='static/images/icons'),
        ),
    ]
